"""Canonical data for the "47 Airbnb Tax Deductions Most Hosts Miss" magnet.

Single source-of-truth for both:
- the PDF render (`_build_47_deductions_pdf.py`)
- the Excel checklist (`_build_47_deductions_xlsx.py`)

Edit here, re-run both builders to keep PDF + Excel in sync.

Reference brief: templates/_briefs/hero-magnet.md (narrative + Daniel's
review checklist). Anything `verify=True` flags an item where the
underlying citation or rate must be re-confirmed against current-year
IRS publications before publish.

⚠ DRAFT — DANIEL TAX-ACCURACY REVIEW REQUIRED BEFORE PUBLISH.
"""

# Sections in the order they appear in the PDF.
SECTIONS = [
    ("Operating expenses",
     "The obvious ones — most hosts still miscount."),
    ("Marketing, platform, and processing",
     "Where revenue and listing investment intersect with deductibility."),
    ("Professional services",
     "Expertise you pay for is fully deductible. Track it."),
    ("Travel + vehicle",
     "Every trip to the property has a deductible mile or hour behind it."),
    ("Depreciation — the biggest deduction most hosts skip",
     "Buildings, improvements, furniture, and the cost-segregation lever."),
    ("Advanced moves most hosts have never heard of",
     "The STR loophole, the Augusta rule, QBI safe harbor, and friends."),
]


# Each entry is a dict with:
#   n          — 1..47
#   section    — one of the SECTIONS section names above
#   name       — short title
#   line       — Schedule E line / Schedule C / "General"
#   irs_ref    — IRS publication or code section
#   typical    — typical $ range / impact
#   missed_because — short paragraph explaining the miss
#   verify     — True if there is a ⚠ verify flag in the brief
ENTRIES = [
    # ----- Operating expenses (1-13) -----
    {"n": 1, "section": "Operating expenses",
     "name": "Cleaning + maintenance fees paid to contractors",
     "line": "Sched E Line 8", "irs_ref": "Pub 527",
     "typical": "$3,000–$15,000/yr",
     "missed_because": "Many hosts net cleaning fees against rental income instead of recording them as a separate expense, which inflates revenue and triggers higher SE-tax exposure on the wrong base.",
     "verify": False},
    {"n": 2, "section": "Operating expenses",
     "name": "Repairs (vs. improvements — treated differently)",
     "line": "Sched E Line 15", "irs_ref": "Pub 527",
     "typical": "$1,000–$8,000/yr",
     "missed_because": "Patch a hole = repair (deduct now). Replace the roof = improvement (depreciate). Hosts conflate the two and either expense improvements (audit risk) or capitalize repairs (overpaid taxes).",
     "verify": False},
    {"n": 3, "section": "Operating expenses",
     "name": "Supplies + consumables",
     "line": "Sched E Line 16", "irs_ref": "Pub 527",
     "typical": "$1,500+ per property",
     "missed_because": "Toilet paper, paper towels, soap, shampoo, batteries, light bulbs, lock batteries. Add up over a year — easily $1,500+ per property, often un-tracked.",
     "verify": True},
    {"n": 4, "section": "Operating expenses",
     "name": "Utilities — electric, gas, water, sewer, trash, propane",
     "line": "Sched E Line 18", "irs_ref": "Pub 527",
     "typical": "$1,800–$6,000/yr",
     "missed_because": "Hosts forget the utility deposit at startup (capitalizable or expensed depending on terms) and the back-bill catch-ups on seasonal properties.",
     "verify": False},
    {"n": 5, "section": "Operating expenses",
     "name": "Internet + cable + streaming services",
     "line": "Sched E Line 18", "irs_ref": "Pub 527",
     "typical": "$600–$1,800/yr per property",
     "missed_because": "WiFi for the rental, smart TV streaming subscriptions dedicated to the rental, security camera cloud storage.",
     "verify": False},
    {"n": 6, "section": "Operating expenses",
     "name": "Property insurance + STR-specific liability rider",
     "line": "Sched E Line 10", "irs_ref": "Pub 527",
     "typical": "$1,200–$3,500/yr",
     "missed_because": "Most hosts catch base insurance; many miss the STR endorsement and standalone short-term rental liability (Proper, Slice).",
     "verify": False},
    {"n": 7, "section": "Operating expenses",
     "name": "Supplemental commercial liability (above platform coverage)",
     "line": "Sched E Line 10", "irs_ref": "Pub 527",
     "typical": "$400–$1,200/yr",
     "missed_because": "Platform coverage has gaps. Standalone commercial liability premium is fully deductible — and most serious hosts should carry it.",
     "verify": False},
    {"n": 8, "section": "Operating expenses",
     "name": "Umbrella policy (rental-allocated portion)",
     "line": "Sched E Line 10", "irs_ref": "Pub 527",
     "typical": "$200–$600/yr",
     "missed_because": "Personal umbrella policies often have a rental-property allocation — only the rental-allocated portion is deductible.",
     "verify": False},
    {"n": 9, "section": "Operating expenses",
     "name": "HOA/COA dues + special assessments",
     "line": "Sched E Line 17 or 19", "irs_ref": "Pub 527",
     "typical": "$0–$8,000/yr",
     "missed_because": "Monthly dues are deductible. One-time special assessments may be capitalizable depending on what they fund (capital improvement to common area = capitalize).",
     "verify": True},
    {"n": 10, "section": "Operating expenses",
     "name": "Property tax + STR-specific local levies",
     "line": "Sched E Line 17", "irs_ref": "Pub 527",
     "typical": "$1,500–$12,000/yr",
     "missed_because": "Including occupancy tax license fees and STR registration fees (not the lodging tax itself, which is collected and remitted separately).",
     "verify": False},
    {"n": 11, "section": "Operating expenses",
     "name": "Mortgage interest (full Form 1098 amount)",
     "line": "Sched E Line 13", "irs_ref": "Form 1098 / Pub 527",
     "typical": "$8,000–$25,000/yr",
     "missed_because": "Catch the entire 1098 amount, not just principal+interest payments. Mortgage insurance premiums may also be deductible.",
     "verify": True},
    {"n": 12, "section": "Operating expenses",
     "name": "Mortgage points (amortized over loan life)",
     "line": "Sched E Line 13", "irs_ref": "Pub 527",
     "typical": "$50–$500/yr",
     "missed_because": "Points paid at closing are deducted over the life of the loan for rentals (different from primary residence). Often missed in year 1.",
     "verify": False},
    {"n": 13, "section": "Operating expenses",
     "name": "Other interest — HELOC + cards used for rental",
     "line": "Sched E Line 14", "irs_ref": "§163 / Pub 527",
     "typical": "Varies",
     "missed_because": "HELOCs explicitly used to renovate or carry the rental, and credit cards used solely for rental expenses. Trace-the-funds rule applies.",
     "verify": True},

    # ----- Marketing / platform / processing (14-18) -----
    {"n": 14, "section": "Marketing, platform, and processing",
     "name": "OTA fees + platform commissions",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$1,500–$12,000/yr",
     "missed_because": "Most hosts net platform fees from revenue rather than expensing them — same trap as netting cleaning fees — wrong revenue base, wrong tax.",
     "verify": False},
    {"n": 15, "section": "Marketing, platform, and processing",
     "name": "Payment processing fees (Stripe / Square / PayPal)",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$200–$2,000/yr",
     "missed_because": "Direct-booking hosts: every transaction's processing cut. Often unrecorded.",
     "verify": False},
    {"n": 16, "section": "Marketing, platform, and processing",
     "name": "Listing photography (and 3D / video walkthroughs)",
     "line": "Sched E Line 6", "irs_ref": "Pub 535",
     "typical": "$300–$1,500 (one-time)",
     "missed_because": "Professional photo shoot is straightforward to expense. Larger productions may cross into 'capitalize' territory — verify per situation.",
     "verify": True},
    {"n": 17, "section": "Marketing, platform, and processing",
     "name": "Listing copy + SEO services",
     "line": "Sched E Line 6", "irs_ref": "Pub 535",
     "typical": "$100–$500/yr",
     "missed_because": "Hiring a copywriter, SEO consultant, or service to optimize the listing — all advertising-line deductible.",
     "verify": False},
    {"n": 18, "section": "Marketing, platform, and processing",
     "name": "Paid ads — Google, Meta, Pinterest",
     "line": "Sched E Line 6", "irs_ref": "Pub 535",
     "typical": "$0–$3,000/yr",
     "missed_because": "Direct-booking hosts only. Google Ads to your own site, Facebook ads, Pinterest promoted pins.",
     "verify": False},

    # ----- Professional services (19-23) -----
    {"n": 19, "section": "Professional services",
     "name": "Property management fees",
     "line": "Sched E Line 12", "irs_ref": "Pub 527",
     "typical": "15–25% of gross",
     "missed_because": "Often deducted automatically by the PM before payout — make sure your books reflect the gross-then-net, not just the net deposits.",
     "verify": False},
    {"n": 20, "section": "Professional services",
     "name": "Tax prep / CPA fees (Schedule E allocated portion)",
     "line": "Sched E Line 11", "irs_ref": "Pub 535",
     "typical": "$300–$1,500/yr",
     "missed_because": "The portion of your CPA bill that relates to Schedule E preparation. A good CPA will break this out on the invoice.",
     "verify": False},
    {"n": 21, "section": "Professional services",
     "name": "Bookkeeping fees",
     "line": "Sched E Line 11", "irs_ref": "Pub 535",
     "typical": "$1,200–$6,000/yr",
     "missed_because": "Monthly bookkeeping services (Bench, Pilot, freelance). Deductible in full when used for the rental business.",
     "verify": False},
    {"n": 22, "section": "Professional services",
     "name": "Legal fees (contracts, leases, eviction, entity setup)",
     "line": "Sched E Line 11", "irs_ref": "§248 / Pub 535",
     "typical": "$0–$2,500/yr",
     "missed_because": "Contract review, lease drafting, eviction, LLC formation costs (organizational costs may need amortization under §248).",
     "verify": True},
    {"n": 23, "section": "Professional services",
     "name": "Consulting + coaching fees",
     "line": "Sched E Line 11", "irs_ref": "Pub 535",
     "typical": "$0–$2,500/yr",
     "missed_because": "STR coaching, business strategy, dynamic-pricing setup consultants, photographer site visits — all deductible.",
     "verify": False},

    # ----- Travel + vehicle (24-28) -----
    {"n": 24, "section": "Travel + vehicle",
     "name": "Mileage at the IRS standard rate",
     "line": "Sched E Line 7", "irs_ref": "Pub 463",
     "typical": "$1,050–$8,400+/yr",
     "missed_because": "2026 IRS rate is 70¢/mile (verify before publish). Every supply run, vendor meeting, banking trip. 3,000 miles/yr × $0.70 = $2,100.",
     "verify": True},
    {"n": 25, "section": "Travel + vehicle",
     "name": "Vehicle actual costs (alternative to standard rate)",
     "line": "Sched E Line 7", "irs_ref": "Pub 463",
     "typical": "Varies by mileage + vehicle",
     "missed_because": "If actual costs exceed the standard rate, track gas, maintenance, depreciation, and insurance allocation. Choose one method per vehicle per year — switch rules apply.",
     "verify": False},
    {"n": 26, "section": "Travel + vehicle",
     "name": "Parking + tolls during business travel",
     "line": "Sched E Line 7", "irs_ref": "Pub 463",
     "typical": "$50–$300/yr",
     "missed_because": "On TOP of the standard mileage rate (these are not included in the per-mile amount).",
     "verify": False},
    {"n": 27, "section": "Travel + vehicle",
     "name": "Out-of-town travel — flights, hotels, rentals",
     "line": "Sched E Line 7", "irs_ref": "Pub 463",
     "typical": "Varies",
     "missed_because": "Travel to inspect, set up, or handle issues at a remote property is deductible with substantiation. Document business purpose for each trip.",
     "verify": False},
    {"n": 28, "section": "Travel + vehicle",
     "name": "Business meals while at the property (50%)",
     "line": "Sched E Line 7", "irs_ref": "§274 / Pub 463",
     "typical": "$100–$500/yr",
     "missed_because": "50% of qualifying meals during business-purpose property visits. Substantiation: receipts + business purpose noted. Deductibility for landlord-only filers must be verified.",
     "verify": True},

    # ----- Depreciation (29-34) -----
    {"n": 29, "section": "Depreciation — the biggest deduction most hosts skip",
     "name": "Building depreciation — 27.5-year straight-line",
     "line": "Sched E Line 20", "irs_ref": "Pub 946",
     "typical": "$8,000–$15,000+/yr",
     "missed_because": "The single largest annual deduction for most rental properties. $400K property, $75K land = $11,800/yr. Most hosts miss it because the math feels intimidating.",
     "verify": False},
    {"n": 30, "section": "Depreciation — the biggest deduction most hosts skip",
     "name": "Improvements depreciation (15-yr or 5/7)",
     "line": "Sched E Line 20", "irs_ref": "Pub 946",
     "typical": "$500–$5,000/yr",
     "missed_because": "New flooring, roof, HVAC, kitchen renovation, deck — each improvement starts its own depreciation schedule on its own asset class.",
     "verify": False},
    {"n": 31, "section": "Depreciation — the biggest deduction most hosts skip",
     "name": "Furniture + appliances depreciation (5-yr or §179)",
     "line": "Sched E Line 20", "irs_ref": "§179 / Pub 946",
     "typical": "$1,500–$8,000 in year-1",
     "missed_because": "Beds, sofas, dining sets, refrigerators, washer/dryer. Often eligible for §179 immediate expensing up to current limits.",
     "verify": True},
    {"n": 32, "section": "Depreciation — the biggest deduction most hosts skip",
     "name": "Bonus depreciation (§168(k))",
     "line": "Sched E Line 20", "irs_ref": "§168(k)",
     "typical": "Varies, very large in year-1",
     "missed_because": "Bonus depreciation rate phases down on a schedule (was 100% through 2022, declining). Verify current-year percentage. Massive impact on year-1 tax bill, especially after a cost-seg study.",
     "verify": True},
    {"n": 33, "section": "Depreciation — the biggest deduction most hosts skip",
     "name": "Cost segregation study (accelerates depreciation)",
     "line": "Sched E Line 20", "irs_ref": "Pub 946",
     "typical": "$20K–$80K year-1 boost",
     "missed_because": "Reclassifies portions of the property (cabinets, lighting, landscaping) from 27.5-year to 5/7/15-year. Study costs $3K–$10K. Worth it on $300K+ properties.",
     "verify": True},
    {"n": 34, "section": "Depreciation — the biggest deduction most hosts skip",
     "name": "Land improvements depreciation (15-year)",
     "line": "Sched E Line 20", "irs_ref": "Pub 946",
     "typical": "$300–$2,500/yr",
     "missed_because": "Driveway paving, fencing, landscaping installation, exterior lighting, parking pad. Often missed because hosts lump them into general 'improvements.'",
     "verify": False},

    # ----- Advanced moves (35-47) -----
    {"n": 35, "section": "Advanced moves most hosts have never heard of",
     "name": "STR Loophole — active vs. passive treatment",
     "line": "Schedule treatment", "irs_ref": "IRC §469",
     "typical": "Saves $5K–$50K+ for high-W2 hosts",
     "missed_because": "Avg guest stay ≤ 7 days + material participation (100+ hrs, more than anyone else) treats the rental as active — losses can offset W-2 / business income. Huge in year 1 with cost seg.",
     "verify": True},
    {"n": 36, "section": "Advanced moves most hosts have never heard of",
     "name": "Pre-startup costs (deductible up to $5K year-1)",
     "line": "Sched E Line 19", "irs_ref": "IRC §195",
     "typical": "$1,500–$5,000 year-1",
     "missed_because": "Costs incurred BEFORE the first guest checks in: scouting trips, market research, consultant fees, training. Most hosts capitalize these or skip entirely.",
     "verify": True},
    {"n": 37, "section": "Advanced moves most hosts have never heard of",
     "name": "Organizational costs (LLC formation)",
     "line": "Sched E Line 19", "irs_ref": "IRC §248",
     "typical": "$300–$1,500",
     "missed_because": "$5K first-year deduction for LLC formation costs (filing fees, legal, registered agent first year). Excess amortizes over 15 years.",
     "verify": True},
    {"n": 38, "section": "Advanced moves most hosts have never heard of",
     "name": "Augusta Rule — rent your own home tax-free",
     "line": "Personal return", "irs_ref": "§280A(g)",
     "typical": "$5,000–$15,000/yr",
     "missed_because": "Rent your PERSONAL residence (not the rental) up to 14 days/yr to your own STR business — income is tax-free to you personally, deductible to the business. Documentation must be airtight.",
     "verify": True},
    {"n": 39, "section": "Advanced moves most hosts have never heard of",
     "name": "Home office deduction",
     "line": "Form 8829 / Sched E Line 19", "irs_ref": "Pub 587",
     "typical": "$500–$3,000/yr",
     "missed_because": "Dedicated room used regularly + exclusively for managing the STR. Two methods: simplified ($5/sq ft up to 300 sq ft) or actual %. Rules differ for Schedule E vs. C filers.",
     "verify": True},
    {"n": 40, "section": "Advanced moves most hosts have never heard of",
     "name": "Cell phone (business-use percentage)",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$300–$800/yr",
     "missed_because": "Allocate the business-use percentage of your cell bill. 50% is a common defensible split for active hosts.",
     "verify": False},
    {"n": 41, "section": "Advanced moves most hosts have never heard of",
     "name": "Home internet (business-use percentage)",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$200–$500/yr",
     "missed_because": "% allocation of your home internet bill that's used for managing the STR. Same logic as cell phone.",
     "verify": False},
    {"n": 42, "section": "Advanced moves most hosts have never heard of",
     "name": "Software + SaaS subscriptions",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$400–$2,000/yr",
     "missed_because": "PriceLabs, Hostfully, AirDNA, Touch Stay, Properly, QuickBooks, password manager, accounting software — all 100% deductible business tools.",
     "verify": False},
    {"n": 43, "section": "Advanced moves most hosts have never heard of",
     "name": "Education + courses (improving existing business)",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$200–$2,000/yr",
     "missed_because": "STR conferences, online courses, books on STR investing, professional development. Must improve an EXISTING trade or business — pre-launch education isn't deductible.",
     "verify": True},
    {"n": 44, "section": "Advanced moves most hosts have never heard of",
     "name": "Bank + credit card fees (dedicated business accounts)",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "$100–$500/yr",
     "missed_because": "Monthly maintenance fees, wire fees, overdraft fees on dedicated business accounts. Mix-use personal accounts don't qualify.",
     "verify": False},
    {"n": 45, "section": "Advanced moves most hosts have never heard of",
     "name": "Refunds + chargebacks given to guests",
     "line": "Net against gross rents", "irs_ref": "Pub 527",
     "typical": "Varies",
     "missed_because": "Refunds typically reduce gross rents (Line 3), not booked as expense. Capture the GROSS revenue + the refund, not just the net deposit.",
     "verify": True},
    {"n": 46, "section": "Advanced moves most hosts have never heard of",
     "name": "Bad debt — unpaid bookings (accrual basis)",
     "line": "Sched E Line 19", "irs_ref": "Pub 535",
     "typical": "Rare",
     "missed_because": "If a direct-booking guest stiffs you and you've already recognized the revenue, the bad debt may be deductible on accrual basis. Limited for cash-basis filers (most landlords).",
     "verify": True},
    {"n": 47, "section": "Advanced moves most hosts have never heard of",
     "name": "QBI deduction — 20% of net rental income (§199A)",
     "line": "Below the line — Form 8995", "irs_ref": "§199A / Rev Proc 2019-38",
     "typical": "20% of net rental income",
     "missed_because": "Not a 'deduction' — a 20% reduction of qualified business income. Safe harbor requires 250+ hrs of rental services per year + separate property records. $30K net rental income × 24% bracket = $1,440 saved.",
     "verify": True},
]


def by_section() -> dict:
    """Return entries grouped by section, in the order SECTIONS defines."""
    out: dict = {}
    for sec_name, _intro in SECTIONS:
        out[sec_name] = [e for e in ENTRIES if e["section"] == sec_name]
    return out


if __name__ == "__main__":
    # Quick integrity check.
    assert len(ENTRIES) == 47, f"Expected 47 entries, got {len(ENTRIES)}"
    for i, e in enumerate(ENTRIES, start=1):
        assert e["n"] == i, f"Entry {i} has wrong n field: {e['n']}"
    flagged = sum(1 for e in ENTRIES if e["verify"])
    print(f"OK - 47 entries - {flagged} flagged for verify - "
           f"{len(SECTIONS)} sections")
