<?php
// Auto-generated from copy/product-pages/bundles/. Hand-edit safe.

return [
  'BUNDLE-01' => [
    'sku'        => 'BUNDLE-01',
    'slug'       => 'first-year-host',
    'name'       => 'The First-Year Host Bundle',
    'short'      => 'First-Year Host',
    'badge'      => '30% off',
    'price'      => '$97',
    'save_amt'   => '$41',
    'save_pct'   => '30%',
    'ala_carte'  => '$138',
    'card_blurb' => 'Underwrite the deal, budget the launch, get the permit, know your floor. 4 workbooks, $41 off à la carte.',
    'h1'         => 'Underwrite the deal. Budget the launch. Get the permit. Know your floor.',
    'sub'        => '4 STR templates for first-year hosts — before guest #1 checks in. $138 à la carte → $97 bundled.',
    'cta'        => 'Get the bundle — $97',
    'pitch'      => [
      'You just closed (or just listed). Now: did you actually buy a deal, or did you buy a hobby? What does the launch actually cost — including the $3K of forgotten line items most hosts miss? Does your city require a permit, and what\'s the fine if you skip? At what occupancy do you stop losing money?',
      'Four workbooks answer all four questions. Bundled at 30% off.',
    ],
    'inside'     => [
      ['sku' => 'ACQ-001', 'name' => 'STR Deal Analyzer (Full)', 'desc' => 'cash-on-cash, DSCR, cap rate, BUY/WALK/NEGOTIATE', 'price' => '$47'],
      ['sku' => 'ACQ-002', 'name' => 'Cost-to-Launch Calculator', 'desc' => '120-item furnishing checklist + Y1 ROI', 'price' => '$27'],
      ['sku' => 'OPS-003', 'name' => 'License/Permit Tracker', 'desc' => 'multi-jurisdiction renewal calendar', 'price' => '$47'],
      ['sku' => 'FIN-002', 'name' => 'Break-Even Occupancy', 'desc' => 'sensitivity grid + stress test', 'price' => '$17'],
    ],
    'why'        => [
      '**The deal didn\'t pencil** but you bought it anyway → ACQ-001 catches this BEFORE close',
      '**The launch budget blew up** by $4K of "I\'ll just grab one" furniture → ACQ-002\'s 120-item list prevents this',
      '**The city\'s STR ordinance had a permit requirement** → OPS-003 surfaces it before the fine arrives',
      '**The first quiet month panicked you** → FIN-002 tells you if you\'re below break-even or just below "good"',
    ],
    'for'        => [
      'First-time STR investors who just closed',
      'New hosts who listed but haven\'t optimized',
      'Buyers under contract who want to verify before close',
      'Anyone whose closest STR-investor friend isn\'t returning their calls',
    ],
    'not'        => [
      'Year 2+ hosts (use Year-2 Operator Bundle instead)',
      'Multi-property operators (use Portfolio Bundle)',
      'Hosts running 5+ properties or running for someone else',
      'Pure long-term landlords (different model)',
    ],
  ],
  'BUNDLE-02' => [
    'sku'        => 'BUNDLE-02',
    'slug'       => 'aspiring-host',
    'name'       => 'The Aspiring Host Bundle',
    'short'      => 'Aspiring Host',
    'badge'      => '42% off',
    'price'      => '$97',
    'save_amt'   => '$71',
    'save_pct'   => '42%',
    'ala_carte'  => '$168',
    'card_blurb' => 'Decide with math, not vibes. 4 workbooks for buyers under contract or hunting their first STR. $71 off.',
    'h1'         => 'Run the timeline. Run the deal. Run the budget. Run the no-money-down option.',
    'sub'        => '4 STR templates for aspiring investors — decide with math, not vibes. $168 à la carte → $97 bundled.',
    'cta'        => 'Get the bundle — $97',
    'pitch'      => [
      'You\'re watching BiggerPockets. You ran the numbers in your head. They sort of work? Maybe? You\'re 6 months from making a real move and you need to stop guessing — about the timeline, the deal, the launch budget, AND the no-money-down arbitrage option you keep wondering about.',
      'Four workbooks let you decide with math.',
    ],
    'inside'     => [
      ['sku' => 'STR-001', 'name' => 'Escape the W2 Planner', 'desc' => 'replacement income + years-to-quit + healthcare bridge', 'price' => '$47'],
      ['sku' => 'ACQ-001', 'name' => 'STR Deal Analyzer (Full)', 'desc' => 'cash-on-cash, DSCR, cap rate, BUY/WALK/NEGOTIATE', 'price' => '$47'],
      ['sku' => 'ACQ-002', 'name' => 'Cost-to-Launch Calculator', 'desc' => '120-item furnishing checklist + Y1 ROI', 'price' => '$27'],
      ['sku' => 'ACQ-003', 'name' => 'Rental Arbitrage Analyzer', 'desc' => 'master-lease no-money-down path', 'price' => '$47'],
    ],
    'why'        => [
      '**When can I quit my W2?** → STR-001 outputs your quit-date based on your portfolio\'s projected cash flow',
      '**Is THIS deal a real deal?** → ACQ-001 underwrites any property — verdict in 5 minutes',
      '**What does the launch actually cost?** → ACQ-002 walks 120+ furnishing items most buyers forget',
      '**Is no-money-down arbitrage actually an option for me?** → ACQ-003 models the master-lease path',
    ],
    'for'        => [
      'Pre-hosts (W2 employee, planning 3-12 months out)',
      'BiggerPockets readers ready to stop reading',
      'Buyers evaluating buy-vs-arbitrage decision',
      'Anyone whose spouse needs to see math',
    ],
    'not'        => [
      'Hosts who already own a property (use First-Year Bundle)',
      'Active multi-property operators',
      'Pure long-term landlords (different model)',
      'Hosts who already use a CPA / lender for underwriting',
    ],
  ],
  'BUNDLE-03' => [
    'sku'        => 'BUNDLE-03',
    'slug'       => 'year-2-operator',
    'name'       => 'The Year-2 Operator Bundle',
    'short'      => 'Year-2 Operator',
    'badge'      => '22% off',
    'price'      => '$147',
    'save_amt'   => '$41',
    'save_pct'   => '22%',
    'ala_carte'  => '$188',
    'card_blurb' => 'Move the lines an experienced host actually controls — RevPAR, fees, listing SEO, claim recovery.',
    'h1'         => 'Stop guessing at occupancy, fees, and listing optimization.',
    'sub'        => '4 workbooks that move the lines an experienced host actually controls. $188 à la carte → $147 bundled.',
    'cta'        => 'Get the bundle — $147',
    'pitch'      => [
      'You\'re past Year 1. You survived launch chaos, paid your cleaner through 50 turnovers, and watched some bookings work and some not. Now you want the optimization layer: revenue per available night, the right cleaning fee, search-rank fixes, and a system for damage claims when things go wrong.',
      'Four workbooks. The moves a Year-2+ host actually controls.',
    ],
    'inside'     => [
      ['sku' => 'FIN-001', 'name' => 'RevPAR Dashboard', 'desc' => 'revenue per available night, ADR, occupancy, momentum', 'price' => '$67'],
      ['sku' => 'REV-001', 'name' => 'Cleaning Fee Optimizer', 'desc' => 'three strategies, search-rank impact, $ delta', 'price' => '$37'],
      ['sku' => 'MKT-001', 'name' => 'Listing SEO Audit', 'desc' => '25 ranking criteria scored, prioritized fix list', 'price' => '$47'],
      ['sku' => 'OPS-002', 'name' => 'Damage Claim + AirCover Log', 'desc' => 'incident log + claim-ready packet', 'price' => '$37'],
    ],
    'why'        => [
      '**You stopped panicking about occupancy** — but you\'re still leaving 12-15% of revenue on the table because RevPAR isn\'t where it should be → FIN-001',
      '**Your cleaning fee was set in Year 1 and never re-audited** — but it might be tanking your booking rank → REV-001',
      '**Your listing ranks fine for some searches, terrible for others** — and you don\'t know why → MKT-001',
      '**Your last damage claim with AirCover paid 35% of what you asked** because the evidence wasn\'t structured → OPS-002',
    ],
    'for'        => [
      'Hosts in Year 2+ of operation',
      '1-3 active properties',
      'Operators past chaos, ready for optimization',
      'Anyone who lost a damage claim because evidence wasn\'t structured',
    ],
    'not'        => [
      'First-time hosts (use First-Year Host Bundle)',
      '5+ property portfolios (use Portfolio Bundle)',
      'Pure-passive PM-managed properties',
      'Hosts on enterprise SaaS (Hostfully, Lodgify Pro) — those bundle similar tools',
    ],
  ],
  'BUNDLE-04' => [
    'sku'        => 'BUNDLE-04',
    'slug'       => 'portfolio',
    'name'       => 'The Portfolio Bundle',
    'short'      => 'Portfolio',
    'badge'      => '35% off',
    'price'      => '$397',
    'save_amt'   => '$213',
    'save_pct'   => '35%',
    'ala_carte'  => '$610',
    'card_blurb' => 'Fourteen workbooks. The full operating system for a multi-property STR portfolio. $213 off.',
    'h1'         => 'Fourteen workbooks. The full operating system for a multi-property STR portfolio.',
    'sub'        => 'Everything that scales beyond one unit. Multi-property P&L, RevPAR dashboard, deal analyzer, audit-defense, claim documentation, the works.',
    'cta'        => 'Get the Portfolio Bundle — $397',
    'pitch'      => [
      '3+ properties. Multiple LLCs. You treat this as a business. Single-property tools don\'t fit anymore — you need the layer above. This bundle is the full operating system for a multi-property STR portfolio: 14 workbooks that handle financial reporting, revenue management, acquisition underwriting, ops, claims, permits, and tax-prep.',
      'This is the bundle TAX-011\'s brief named at $397. Honoring that.',
    ],
    'inside'     => [
      ['sku' => 'TAX-011', 'name' => 'Multi-Property Master P&L', 'desc' => '', 'price' => '$97'],
      ['sku' => 'FIN-001', 'name' => 'RevPAR Dashboard', 'desc' => '', 'price' => '$67'],
      ['sku' => 'ACQ-001', 'name' => 'STR Deal Analyzer (Full)', 'desc' => '', 'price' => '$47'],
      ['sku' => 'OPS-002', 'name' => 'Damage Claim + AirCover Log', 'desc' => '', 'price' => '$37'],
      ['sku' => 'OPS-003', 'name' => 'License/Permit Tracker', 'desc' => '', 'price' => '$47'],
      ['sku' => 'REV-001', 'name' => 'Cleaning Fee Optimizer', 'desc' => '', 'price' => '$37'],
      ['sku' => 'MKT-001', 'name' => 'Listing SEO Audit', 'desc' => '', 'price' => '$47'],
      ['sku' => 'FIN-002', 'name' => 'Break-Even Occupancy', 'desc' => '', 'price' => '$17'],
      ['sku' => 'ACQ-002', 'name' => 'Cost-to-Launch Calculator', 'desc' => '', 'price' => '$27'],
      ['sku' => 'STR-001', 'name' => 'Escape the W2 Planner', 'desc' => '', 'price' => '$47'],
      ['sku' => 'TAX-002', 'name' => 'Single-Property P&L Tracker (prior catalog)', 'desc' => '', 'price' => '$47'],
      ['sku' => 'TAX-004', 'name' => 'Schedule E Tax-Prep Workbook', 'desc' => '', 'price' => '$47'],
      ['sku' => 'GST-001', 'name' => 'Welcome Book', 'desc' => '', 'price' => '$17'],
      ['sku' => 'OPS-001', 'name' => 'Cleaner Turnover Checklist', 'desc' => '', 'price' => '$12'],
    ],
    'why'        => [
      '**What\'s the portfolio actually doing?** TAX-011 + FIN-001 = consolidated income + RevPAR',
      '**Should we buy the next property?** ACQ-001 + ACQ-002 + STR-001 + FIN-002',
      '**Where\'s revenue leaking?** REV-001 + MKT-001',
      '**Where\'s risk leaking?** OPS-002 + OPS-003',
      '**Year-end tax filing?** TAX-002 + TAX-004',
      '**Day-to-day ops?** GST-001 + OPS-001',
    ],
    'for'        => [
      '3+ STR properties',
      'Multi-LLC portfolio operators',
      'Operators who treat this as a business, not a hobby',
      'Buyers using DSCR / commercial loans',
    ],
    'not'        => [
      'Single-property hosts (use First-Year or Year-2 bundles)',
      'Property managers serving owners (use Pro Manager Bundle)',
      'Pure-passive Schedule E hosts who outsource everything',
      'Hosts running 1-2 properties as a side hustle',
    ],
  ],
  'BUNDLE-05' => [
    'sku'        => 'BUNDLE-05',
    'slug'       => 'pro-manager',
    'name'       => 'The Pro Manager Bundle',
    'short'      => 'Pro Manager',
    'badge'      => 'Launch tier',
    'price'      => '$497',
    'save_amt'   => '',
    'save_pct'   => '',
    'ala_carte'  => '',
    'card_blurb' => 'Seven workbooks. The owner-facing reporting layer plus the operating math underneath. White-labelable.',
    'h1'         => 'Seven workbooks. The owner-facing reporting layer plus the operating math underneath.',
    'sub'        => 'White-labelable. Bring your own owner. The full B2B stack for property managers running 5+ owner properties.',
    'cta'        => 'Get the Pro Manager Bundle — $497',
    'pitch'      => [
      'You\'re a property manager / co-host running 5+ properties for other people. Your owners want monthly statements that look professional. Your portfolio needs the same operating math any serious STR operator runs (RevPAR, claims, permits, listing SEO, cleaning fee). And at year-end, K-1s and 1099-NECs need to be defensible.',
      'This bundle is the B2B stack: PAM-001 Owner Reporting Dashboard at the top, the same operating workbooks any portfolio operator uses underneath. White-labelable.',
    ],
    'inside'     => [
      ['sku' => 'PAM-001', 'name' => 'Owner Reporting Dashboard (B2B)', 'desc' => '', 'price' => '$197'],
      ['sku' => 'TAX-011', 'name' => 'Multi-Property Master P&L', 'desc' => '', 'price' => '$97'],
      ['sku' => 'FIN-001', 'name' => 'RevPAR Dashboard', 'desc' => '', 'price' => '$67'],
      ['sku' => 'OPS-002', 'name' => 'Damage Claim + AirCover Log', 'desc' => '', 'price' => '$37'],
      ['sku' => 'OPS-003', 'name' => 'License/Permit Tracker', 'desc' => '', 'price' => '$47'],
      ['sku' => 'MKT-001', 'name' => 'Listing SEO Audit', 'desc' => '', 'price' => '$47'],
      ['sku' => 'REV-001', 'name' => 'Cleaning Fee Optimizer', 'desc' => '', 'price' => '$37'],
    ],
    'why'        => [
    ],
    'for'        => [
      'Property managers (5+ owner properties)',
      'Co-hosts managing portfolios for absent owners',
      'White-label-needing PM operations',
      'B2B operators preparing year-end 1099 + K-1',
    ],
    'not'        => [
      'Self-managed solo hosts (use First-Year or Year-2 bundles)',
      'Solo investors managing only their own properties (use Portfolio Bundle)',
      'PMs running enterprise SaaS (Hostfully, Lodgify Pro) — those bundle similar tools',
      'Pure short-term operators (no owner relationships to serve)',
    ],
  ],
];