<?php
// Auto-generated from copy/product-pages/. Hand-edit safe.

return [
  'TAX-001' => [
    'sku'        => 'TAX-001',
    'slug'       => 'mileage-log',
    'name'       => 'The Mileage Log',
    'category'   => 'Tax & Accounting',
    'price'      => '$17',
    'badge'      => 'Wave 1',
    'card_blurb' => 'Audit-defensible mileage log. Auto-applies the 2026 IRS rate. Schedule E export built in.',
    'mock_sub'   => 'Every business mile, audit-defensible. 2026 IRS rate auto-applied.',
    'h1'         => 'The deduction your CPA wishes you\'d tracked.',
    'sub'        => 'IRS-aligned mileage log for Airbnb and STR hosts. Auto-applies the 2026 standard rate. Schedule E export built in.',
    'pitch'      => [
      'You drove 38 miles to Home Depot for the master bathroom faucet. Another 22 to drop linens at the cleaner. Another 47 to meet the HVAC guy. By the end of the year you have driven somewhere between 1,800 and 4,200 miles for the property, and you remember almost none of them.',
      'The IRS allows the standard mileage rate per business mile on Schedule E. At the 2026 rate of 70¢/mile, 3,000 miles is **$2,100 in deductions**. Most hosts take zero, because reconstructing a year of trips from memory feels like fraud and feels like work.',
      'This template makes it 30 seconds per trip. Date, purpose, miles. The rate auto-applies. The Schedule E rollup auto-builds. End of year you print one page and hand it to your CPA.',
    ],
    'inside'     => [
      ['name' => 'Start', 'desc' => 'YTD deduction front-and-center. Trip count. Average miles per trip. Quick-add link.'],
      ['name' => 'Trip Log', 'desc' => 'date, from, to, purpose, business miles, personal miles, notes. 1,000-row capacity.'],
      ['name' => 'Schedule E Export', 'desc' => 'auto-built table: month / business miles / deduction at the active IRS rate. Print-ready, single page, ready for your CPA.'],
      ['name' => 'Audit-Defense Pack', 'desc' => 'what the IRS actually wants in a mileage log if they ask. Field-by-field reasoning. Date / purpose / miles / contemporaneous-record stamp.'],
      ['name' => 'Settings', 'desc' => 'active tax year, IRS rate per year (2024/2025/2026 pre-loaded — edit as IRS publishes), property list dropdown source.'],
    ],
    'for'        => [
      'Airbnb / VRBO hosts who drive to their property for any reason',
      'Multi-property operators with regular supply / vendor / inspection runs',
      'Hosts who have done their own taxes and skipped mileage every year',
      'Single-property hosts doing their own Schedule E in TurboTax',
      'Anyone whose 2025 tax return left mileage at $0',
    ],
    'not'        => [
      'Hosts whose CPA already runs a mileage app for them',
      'Hosts who never visit the property — fully remote with a PM doing everything',
      'Hosts looking for a GPS auto-tracker app — this is a log, not an app',
      'Commercial fleet operators (use a fleet-grade SaaS)',
    ],
    'faq'        => [
      ['q' => 'Is the IRS rate updated automatically?', 'a' => 'The active rate cell on Settings is editable. Pre-loaded with the 2024, 2025, and 2026 IRS published rates. When the IRS publishes the next year\'s rate, change one cell. We post rate updates at thestrledger.com/irs-rate.'],
      ['q' => 'What counts as a business mile?', 'a' => 'Travel between properties, supply runs, vendor meetings, contractor coordination, banking related to the rental, inspections, in-person tax-prep meetings. Does NOT include: your daily commute (you don\'t have one), personal errands you tacked a property stop onto, or scenic drives.'],
      ['q' => 'What if I drove for both business and personal in one trip?', 'a' => 'The Trip Log has a "personal miles" column. Subtract those from total. The IRS wants only business miles on Schedule E.'],
      ['q' => 'Do I need GPS proof?', 'a' => 'No. The IRS wants a "contemporaneous record" — meaning logged at or near the time of the trip, not reconstructed at year-end. Our template includes a contemporaneous-record stamp so the audit-defense pack reads cleanly.'],
      ['q' => 'Schedule E or Schedule C?', 'a' => 'Standard rental income → Schedule E. STR with average stay ≤ 7 nights and material participation can flip to Schedule C (with self-employment tax implications). The template\'s Audit-Defense tab shows both. Default behavior is Schedule E.'],
      ['q' => 'Does it work in Google Sheets?', 'a' => 'Yes. The IRS-rate auto-apply and the SUMIFS-based Schedule E rollup all work natively in Sheets.'],
    ],
  ],
  'GST-001' => [
    'sku'        => 'GST-001',
    'slug'       => 'welcome-book',
    'name'       => 'The Welcome Book',
    'category'   => 'Guest Experience',
    'price'      => '$17',
    'badge'      => 'Wave 1',
    'card_blurb' => 'Editable 9-section welcome book. Print, frame, QR. Built for hosts running a real business.',
    'mock_sub'   => 'A welcome book guests actually read.',
    'h1'         => 'Stop emailing guests Google Docs.',
    'sub'        => 'A 9-section editable welcome book — print it, frame it, QR it. Built for Airbnb and VRBO hosts who run a real business.',
    'pitch'      => [
      'You did not get into hosting to answer "what\'s the wifi" at 11:47pm. You did, though, and you keep doing it because the welcome doc you wrote two years ago in Google Docs is missing trash day, the streaming login, the hot tub instructions, the fastest urgent-care, and basically every detail that does not occur to you until a guest needs it.',
      'This is a single 9-section welcome book. Editable Excel. Matching PDF. Print-ready. QR-ready. Covers what guests actually ask. Looks like your business is a business.',
      'Edit it once per property. Re-export the PDF when something changes. Done.',
    ],
    'inside'     => [
      ['name' => 'Welcome', 'desc' => 'cover, host first name, property name, stay dates auto-display'],
      ['name' => 'Arrival', 'desc' => 'door code, parking, where to park the second car, late-arrival instructions'],
      ['name' => 'WiFi + Tech', 'desc' => 'network name, password, TV inputs, streaming logins, smart-lock how-to, thermostat'],
      ['name' => 'House Rules', 'desc' => 'quiet hours, smoking, pets, max guests, parties — section-headed so it reads, not lectures'],
      ['name' => 'Local Guide', 'desc' => 'restaurants, coffee, groceries, urgent care, vet — distance, phone, notes'],
      ['name' => 'Trash + Recycling', 'desc' => 'pickup day, bin location, sorting rules'],
      ['name' => 'Departure', 'desc' => 'checkout time, key return, last-minute tasks (dishwasher? thermostat?)'],
      ['name' => 'Emergency', 'desc' => 'hospital, police non-emergency, 24-hr vet, utility outage numbers — host phone auto-pulled from Welcome tab'],
    ],
    'for'        => [
      'Airbnb / VRBO / direct-booking hosts who want a polished welcome',
      'Newly-launched hosts who need a welcome book today',
      'Multi-property operators who want one template, edited per property',
      'Hosts whose guests text them at 11pm asking about wifi',
      'Hosts who want to print AND send a PDF AND post a QR code',
    ],
    'not'        => [
      'Hosts who want to handwrite a binder for "the cabin feel"',
      'Hosts who need a hospitality consultant to interview their property',
      'Hosts who want a SaaS app with guest-portal logins',
      'Hosts who already use Hostfully / Touch Stay and need an integration',
      'Hosts who need translations into 14 languages out of the box',
    ],
    'faq'        => [
      ['q' => 'Can I edit it?', 'a' => 'Every cell. No password protection, no protected ranges. Edit, rebrand, re-color — it is your file.'],
      ['q' => 'Does it work in Google Sheets?', 'a' => 'Yes. Open via Google Drive → Open with Google Sheets. Some Excel-specific formatting may shift slightly; the content travels intact.'],
      ['q' => 'How do I make a QR code?', 'a' => 'Export your finished workbook to PDF, host it anywhere (Google Drive shareable link, Dropbox, your own site), generate a QR code pointing at the URL (any free QR generator). Place the QR on a small printed placard at check-in.'],
      ['q' => 'Will it look the same when printed?', 'a' => 'Yes. The print area is set on every guest-facing tab. The Host Reference tab is hidden by default in the PDF export — it stays visible for you in the workbook.'],
      ['q' => 'Is the Host Reference tab really hidden from guests?', 'a' => 'Hidden, but not encrypted. If a technically-curious guest opens the .xlsx, they can unhide it. We strongly recommend you only ever share the PDF export with guests, not the .xlsx itself.'],
      ['q' => 'Refunds?', 'a' => '14 days, no questions. Email hello@thestrledger.com.'],
    ],
  ],
  'OPS-001' => [
    'sku'        => 'OPS-001',
    'slug'       => 'turnover-checklist',
    'name'       => 'The Turnover Checklist',
    'category'   => 'Operations / Cleaning',
    'price'      => '$12',
    'badge'      => 'Wave 1',
    'card_blurb' => 'Printable cleaner checklist + scorecard. See which cleaner actually does the work.',
    'mock_sub'   => 'Turnover chaos has a spreadsheet.',
    'h1'         => 'Turnover chaos has a spreadsheet.',
    'sub'        => 'A printable cleaner checklist your cleaner uses on the property — plus a scorecard tab you fill in after, so you can see which cleaner actually does the work.',
    'pitch'      => [
      'Your cleaner says she finished. Then a guest checks in and finds hair in the shower drain, the coffee filter still in the basket, and the trash bag tied but not removed. You apologize, refund $40, and lose the 5-star.',
      'The problem is not your cleaner. The problem is there is no shared definition of "done." Every cleaner has their own routine. Every property has its own quirks. Every host says "the usual" and assumes the message landed.',
      'This is a single-page printed checklist your cleaner takes into the property — every room, every task, every supply check, in turnover order. Plus a one-page Scorecard you fill in after each turn so you can see which cleaner is consistently red on "trash removed" and have the conversation with data.',
    ],
    'inside'     => [
      ['name' => 'Cover', 'desc' => 'your property name, your cleaner\'s name, the season. Edit once.'],
      ['name' => 'Pre-Arrival Checklist', 'desc' => 'printable. Bedrooms, bathrooms, kitchen, living, exterior, supplies, hot tub / pool / fire pit if applicable. ~80 line items.'],
      ['name' => 'Quick-Score Scorecard', 'desc' => '10-row tab you fill in after each turnover. Auto-rolls into a per-cleaner average, a 30-day trend, and a "next conversation" flag.'],
      ['name' => 'Supply Pars', 'desc' => 'one row per consumable (TP, paper towels, dish soap, coffee, shampoo). When score < target, the row turns red.'],
      ['name' => 'Photo-Standard Reference', 'desc' => 'a 1-page guide of what "made bed" looks like, what "drain hair removed" looks like, what "coffee station reset" looks like. Print and tape inside the supply closet.'],
      ['name' => 'Settings', 'desc' => 'your cleaner names, properties, supply pars.'],
    ],
    'for'        => [
      'Hosts whose cleaner skips the same 3 things every turn',
      'Multi-property hosts who use 2+ cleaners and need consistency',
      'Co-hosts and PMs who track cleaner performance across an owner portfolio',
      'Hosts switching from a "she said it\'s fine" cleaner to data',
      'Anyone who has refunded a guest because of a cleaning miss',
    ],
    'not'        => [
      'Hosts who clean their own property and want a personal checklist',
      'Hosts using a full SaaS like Properly or Breezeway and want an integration',
      'Hosts who want commercial-grade cleaning SOPs for a 50-unit portfolio',
      'Hosts who have one cleaner forever and trust her completely',
    ],
    'faq'        => [
      ['q' => 'Will my cleaner actually use a paper checklist?', 'a' => 'Most do. Cleaners who already do the job well like the checklist because it stops you re-explaining "the usual" — they can prove they finished. Cleaners who fight the checklist usually have a reason worth knowing about.'],
      ['q' => 'Can I customize it for my property?', 'a' => 'Yes. Every line item is editable. Add a hot tub row. Remove the hardwood-mop row if you have all carpet. Add the specific drawer where the spare batteries live. Re-print.'],
      ['q' => 'Is the Scorecard for me or for the cleaner?', 'a' => 'You. Fill it in after the turn or during your spot-check. Your cleaner does not need to see the score every time — but most appreciate seeing "92% on 30-day average" once a month.'],
      ['q' => 'Does it print clean on letter and A4?', 'a' => 'Yes. Print area set, margins tight, single-page per checklist. International A4 hosts: paper size override is a 2-click change in Excel.'],
      ['q' => 'Refunds?', 'a' => '14 days, no questions. Email hello@thestrledger.com.'],
    ],
  ],
  'TAX-002' => [
    'sku'        => 'TAX-002',
    'slug'       => 'pl-tracker',
    'name'       => 'The P&L Tracker',
    'category'   => 'Tax & Accounting',
    'price'      => '$27',
    'badge'      => 'Wave 2',
    'card_blurb' => 'Schedule E P&L for one property. IRS-mapped categories. 27.5-yr depreciation built in.',
    'mock_sub'   => 'Close your year before April does.',
    'h1'         => 'Close your year before April does.',
    'sub'        => 'A Schedule E P&L for Airbnb and STR hosts — IRS line-mapped categories, built-in 27.5-yr depreciation calculator, CPA-ready output. One property, fully accounted.',
    'pitch'      => [
      'Two things sink most single-property hosts at tax time.',
      '**First**, your spreadsheet uses "internet," "Wi-Fi," "comcast," and "ISP" all in different rows. Your CPA opens it in March, sees 200 expense entries that don\'t roll up to anything, and bills you three hours to clean it up. Or worse — does it imperfectly and your Schedule E walks in soft.',
      '**Second**, you skip depreciation. A $400,000 property with $75,000 in land = roughly **$11,800/year** in straight-line residential rental depreciation. At a 24% federal bracket, that\'s $2,832/year in tax saved. You don\'t take it because the IRS rules feel complicated and the workbook in your accountant\'s Dropbox is from 2018.',
    ],
    'inside'     => [
      ['name' => 'Welcome', 'desc' => 'how the workbook maps to IRS Schedule E. Print-ready, single page.'],
      ['name' => 'Property Info', 'desc' => 'address, purchase price, closing costs, loan terms, in-service date, days rented, personal-use days. Auto-flags Pub 527\'s 14-day / 10% threshold.'],
      ['name' => 'Revenue Log', 'desc' => '1,000-row capacity. Date, guest, channel (Airbnb / VRBO / Booking.com / Direct / Other), gross, platform fee, cleaning fee collected, net, nights. Nights column drives the STR loophole eligibility check.'],
      ['name' => 'Expense Log', 'desc' => '2,000-row capacity. 17 expense categories, all Schedule E line-mapped, dropdown-enforced. No miscategorized rows.'],
      ['name' => 'Monthly P&L', 'desc' => '12 months × 17 categories. Net income row with green/red conditional formatting. Donut chart of expense composition.'],
      ['name' => 'Depreciation', 'desc' => 'straight-line 27.5-yr residential rental, mid-month convention. Pulls cost basis from Property Info. Land-value input + depreciable basis + annual + current-year amounts. Auto-fills Schedule E Line 20.'],
      ['name' => 'Schedule E Summary', 'desc' => 'IRS Schedule E Part I line totals (Lines 3–26a). Audit-defense block: STR loophole eligibility (IRC §469), 14-day personal-use test (Pub 527), QBI safe-harbor flag (§199A). Schedule E vs Schedule C routing footnote. Print-ready.'],
      ['name' => 'Settings', 'desc' => 'active tax year (drives all date filters), Schedule E vs Schedule C classification, 17-category dropdown source, year-end archive ritual.'],
    ],
    'for'        => [
      'Airbnb / VRBO hosts who own ONE rental property',
      'Hosts whose CPA charges by the hour to "clean up" their spreadsheet',
      'First-year hosts who need to file Schedule E in April',
      'Hosts leaving depreciation off their Schedule E because the math felt scary',
      'Anyone who has paid their CPA "just to have someone else do it"',
    ],
    'not'        => [
      'Hosts who own 2+ properties (see Portfolio Master)',
      'Hosts who hand over a shoebox and let the CPA bill what they bill',
      'Hosts on Schedule C (full-time STR with material participation — see Schedule C variant)',
      'Hosts with cost-segregation studies and bonus-depreciation flags (see Portfolio Master)',
      'Hosts who use QuickBooks Self-Employed and want a QB import',
    ],
    'faq'        => [
      ['q' => 'Is the depreciation calculation IRS-correct?', 'a' => 'For straight-line residential rental real property over 27.5 years using the mid-month convention, yes — that\'s the IRS-prescribed method for rental buildings placed in service after 1986 (Pub 527). The math is straightforward: depreciable basis ÷ 27.5 = annual; first-year prorated by months in service. The workbook\'s Depreciation tab walks the calculation transparently so your CPA can verify in one glance.'],
      ['q' => 'Why isn\'t asset-by-asset depreciation included?', 'a' => 'Furniture (5-yr), appliances (5-yr), improvements (15-yr), bonus depreciation, cost segregation — those live in the Portfolio Master ($97 own-site) because the inputs and forms get materially more complex. Most single-property hosts get 80%+ of their depreciation from the building alone, which is what this tab handles.'],
      ['q' => 'Does this support Schedule C (active trade or business)?', 'a' => 'Settings tab has a Schedule E vs Schedule C dropdown. The Schedule E Summary tab\'s net-income footnote routes to Line 26 (E) or Line 31 (C) accordingly. The form structure is the same — what changes is whether SE tax (15.3%) applies.'],
      ['q' => 'What if I bought the property mid-year?', 'a' => 'The Depreciation tab handles mid-month convention automatically. Enter your in-service date on Property Info; the calculator computes months-in-service for the first calendar year. Subsequent full years auto-fill at the full annual amount.'],
      ['q' => 'What if I\'m in year three and never tracked depreciation before?', 'a' => 'Two options. (1) The Depreciation tab has an "Implied prior accumulated" helper that estimates what you should have taken. (2) Have your CPA file Form 3115 (Application for Change in Accounting Method) to catch up missed depreciation in one year. The latter is the right answer for amounts over a few thousand. We\'re not your CPA — confirm before filing.'],
      ['q' => 'Etsy version vs own-site version — what\'s different?', 'a' => 'Same workbook. The Etsy version is $27, the own-site version is $47. Price difference reflects storefront economics (Etsy\'s discoverability + lower-AOV audience vs own-site\'s direct-to-list willingness-to-pay). Both files include the same upgrade banner pointing at the Portfolio Master.'],
    ],
  ],
  'TAX-003' => [
    'sku'        => 'TAX-003',
    'slug'       => '1099-nec-tracker',
    'name'       => 'The 1099-NEC Tracker',
    'category'   => 'Tax & Compliance',
    'price'      => '$17',
    'badge'      => 'Wave 2',
    'card_blurb' => '1099-NEC tracker. Auto-flags every contractor over $600. January in 15 minutes.',
    'mock_sub'   => 'The $600 threshold, tracked automatically.',
    'h1'         => 'The $600 threshold, tracked automatically.',
    'sub'        => 'A 1099-NEC tracker for Airbnb and STR hosts. Auto-flags every contractor who crosses $600. W-9 status traffic-light. January is 15 minutes instead of 15 hours.',
    'pitch'      => [
      'You paid your cleaner $185 fourteen times this year. That\'s $2,590. She needs a 1099-NEC from you by January 31.',
      'Your handyman? Six visits at varying amounts — did he hit $600? You don\'t know. Your landscaper? Your emergency plumber? The pool guy who came in May?',
      'Most hosts have no idea who crossed the IRS $600 threshold until their CPA asks in January, and then they spend two days piecing it together from Venmo screenshots, bank statements, and text messages. Some hosts skip 1099s entirely and risk **$60–$660 per missing form** in IRS penalties (Pub 1220) — plus losing the deduction on those payments.',
    ],
    'inside'     => [
      ['name' => 'Start', 'desc' => 'count of 1099s required, ready, blocked-on-W-9. Total $ volume. The number you need at a glance.'],
      ['name' => 'Contractors Directory', 'desc' => '50-contractor capacity. Name, business name, EIN/SSN, full address, email, phone, services, W-9 on file (Yes/No), W-9 received date.'],
      ['name' => 'Payment Log', 'desc' => '2,000-row capacity. Date, contractor (dropdown from Directory), amount, payment method (7 dropdowns: Venmo, Zelle, Check, Cash, ACH, Credit Card, Other), property tag, description, notes.'],
      ['name' => '1099 Prep Dashboard', 'desc' => 'auto-calculated. YTD per contractor. **Red YES** when ≥ $600. Green ✓ Ready (W-9 on file) or yellow ⚠ Need W-9 status. Summary roll-up of count + $ volume.'],
      ['name' => 'W-9 Request Templates', 'desc' => '3 email templates (first ask, follow-up, year-end-deadline) with merge tokens for the contractor\'s name and amount paid.'],
      ['name' => 'Settings', 'desc' => 'editable IRS threshold (default $600 — IRS may adjust), active tax year, IRS Pub 1220 penalty schedule reference.'],
    ],
    'for'        => [
      'Hosts with cleaning, handyman, landscaping, or other contractor relationships',
      'Multi-property hosts tracking payments across properties',
      'Anyone whose CPA asked for a 1099 list last January and got nothing',
      'Hosts paying via Venmo / Zelle who want a clean paper trail',
      'First-time STR owners who are not sure who needs a 1099',
    ],
    'not'        => [
      'Hosts whose only "vendor" is the Airbnb platform itself',
      'W-2 employers (1099-NEC is for non-employee compensation; payroll uses W-2)',
      'Hosts running a full QuickBooks setup with vendor management',
      'Hosts using a bookkeeping service that already handles 1099 prep',
      'International hosts (1099 is US-tax-only)',
    ],
    'faq'        => [
      ['q' => 'What is a 1099-NEC?', 'a' => 'Form 1099-NEC ("Nonemployee Compensation") reports payments of $600 or more in a calendar year to a person or unincorporated business who is not your employee, for services rendered. Required since the 2020 tax year (replaced 1099-MISC for this purpose). Filed by January 31 of the year following payment.'],
      ['q' => 'Who needs a 1099 from me?', 'a' => 'Any individual or unincorporated business (sole prop, single-member LLC) you paid $600+ in a calendar year for services. Does NOT apply to: corporations (with limited exceptions like attorneys), payments via credit card or third-party platforms (those are reported on 1099-K by the platform — but Venmo/Zelle person-to-person are NOT exempt from 1099-NEC), and product-only purchases.'],
      ['q' => 'What\'s the W-9 traffic light for?', 'a' => 'You can\'t issue a 1099 without the contractor\'s tax information. The W-9 form (filled out by the contractor and given to you) provides their legal name, address, and EIN/SSN. The dashboard\'s status column shows green ✓ Ready (W-9 on file) or yellow ⚠ Need W-9. Chase yellow rows in November/December — not January.'],
      ['q' => 'What if I pay via Venmo or Zelle — does that exempt me?', 'a' => 'No. Person-to-person Venmo/Zelle payments to contractors are NOT covered by the platform\'s 1099-K reporting. You are still responsible for the 1099-NEC. Business-mode Venmo payments may be reported on 1099-K depending on the platform\'s current policy and the recipient\'s business setup. When in doubt, treat Venmo/Zelle as "your responsibility to 1099."'],
      ['q' => 'What about my property manager?', 'a' => 'If your PM is a corporation, no 1099 typically required. If sole prop / single-member LLC, yes — and PM payments are often well over $600. The dashboard shows them either way.'],
      ['q' => 'Can I file the 1099s from this workbook?', 'a' => 'No — the workbook prepares the data. To file, use a service like Track1099, Tax1099.com, or QuickBooks. Most cost $3–5 per form. Or your CPA files them. The dashboard exports clean.'],
    ],
  ],
  'TAX-004' => [
    'sku'        => 'TAX-004',
    'slug'       => 'schedule-e-tax-prep',
    'name'       => 'The Schedule E Workbook',
    'category'   => 'Tax & Accounting',
    'price'      => '$47',
    'badge'      => '',
    'card_blurb' => 'Year-end Schedule E workbook. Every line pre-mapped. Audit-defense block built in.',
    'mock_sub'   => 'Hand your CPA a finished Schedule E.',
    'h1'         => 'Hand your CPA a finished Schedule E.',
    'sub'        => 'Year-end tax-prep workbook for Airbnb and STR hosts — every Schedule E line pre-mapped, depreciation included, audit-defense block built in.',
    'pitch'      => [
      'Your CPA opens your spreadsheet in March. Two hours later, she texts: "your categories don\'t map to Schedule E — I rebuilt it." Three hours billable. Or you DIY in TurboTax and stare at Line 5 because your Airbnb summary, Vrbo summary, and Direct-booking spreadsheet don\'t agree on what your gross rents actually were.',
      'This workbook is the bridge between your messy bookkeeping and a CPA-ready Schedule E. Every expense category dropdown-enforced and pre-mapped to a Schedule E line number. Built-in 27.5-year straight-line depreciation. Audit-defense block that auto-flags STR loophole eligibility, the 14-day personal-use test, and QBI safe harbor — three of the biggest items most CPAs forget to ask about.',
      'Hand the Schedule E Summary tab to your CPA. They copy your numbers straight into the form. Bill drops from 12 hours to 2.',
    ],
    'inside'     => [
      ['name' => 'Welcome', 'desc' => 'Schedule E mapping note, how-to, year-end ritual'],
      ['name' => 'Property Info', 'desc' => 'address, purchase, loan, in-service, days rented, personal-use'],
      ['name' => 'Revenue Log', 'desc' => '1,000-row capacity, multi-channel rollup'],
      ['name' => 'Expense Log', 'desc' => '2,000-row capacity, 17 Schedule E-mapped categories, dropdown-enforced'],
      ['name' => 'Monthly P&L', 'desc' => '12 × 17 matrix with green/red net income'],
      ['name' => 'Depreciation', 'desc' => '27.5-yr SL building depreciation, mid-month convention, auto-fills Line 20'],
      ['name' => 'Schedule E Summary', 'desc' => 'IRS Lines 3–26a, audit-defense block, print-ready'],
      ['name' => 'Settings', 'desc' => 'active tax year, Schedule E vs C, archive ritual'],
    ],
    'for'        => [
      'Airbnb / VRBO hosts filing Schedule E',
      'Single-property and small-portfolio hosts (1-3 rentals)',
      'Hosts whose CPA charges by the hour to clean up their books',
      'DIY filers using TurboTax / FreeTaxUSA',
      'First-year hosts who\'ve never seen Schedule E before',
    ],
    'not'        => [
      'Hosts whose CPA already runs the year-end on their own software',
      'Multi-LLC hosts needing entity consolidation (see Portfolio Master)',
      'Schedule C filers (use TAX-012 instead)',
      'Pure-passive hosts who never log a thing all year',
      'Hosts with cost-seg studies + bonus-depreciation overlays (use Portfolio Master)',
    ],
    'faq'        => [
      ['q' => 'Etsy version vs own-site version — what\'s different?', 'a' => 'Both versions ship the same workbook at MVP. Etsy is $47 reflecting Etsy\'s discoverability + lower-AOV audience economics. Own-site is $97 reflecting the direct-buyer willingness-to-pay for the same tool. Both upgrade-ladder to the Portfolio Master.'],
      ['q' => 'Is this a substitute for a CPA?', 'a' => 'No. It\'s the workbook your CPA wishes you\'d shown up with. Schedule E filing is straightforward enough that DIY in TurboTax works for many hosts; for everyone else, this workbook still cuts CPA prep time roughly in half.'],
      ['q' => 'Schedule E or Schedule C?', 'a' => 'The Settings tab has a dropdown. The Schedule E Summary tab\'s net-income footnote routes to Line 26 (E) or Line 31 (C) accordingly. Most hosts default to E. If you provide substantial services (cleaning during stay, meals, transportation), see TAX-008 SE Tax Calculator first to walk the decision.'],
      ['q' => 'Multi-property?', 'a' => 'This is single-property. The Portfolio Master at thestrledger.com/portfolio-master ($97) handles multi-property consolidation, asset-by-asset depreciation, LLC-by-LLC rollup. Or save with the Portfolio Bundle ($397).'],
      ['q' => 'Refunds?', 'a' => '14 days, no questions. Email hello@thestrledger.com.'],
    ],
  ],
  'GST-002' => [
    'sku'        => 'GST-002',
    'slug'       => 'house-rules-builder',
    'name'       => 'The House Rules Builder',
    'category'   => 'Guest Experience',
    'price'      => '$17',
    'badge'      => '',
    'card_blurb' => 'Wizard-built house rules. 25–40 specific, defensible items. Damage claims succeed faster.',
    'mock_sub'   => 'House rules that hold up in a damage claim.',
    'h1'         => '25-40 specific, defensible rules. No more blank textarea on Airbnb.',
    'sub'        => 'Wizard-style 6-section walkthrough → printable + listing-ready house rules document. Damage claims succeed faster when the rule was specific.',
    'pitch'      => [
      'Most hosts list 4 generic rules: "no smoking, no pets, no parties, quiet hours after 10pm." When a guest plays music until 2am, "be respectful" doesn\'t help your damage claim or your neighbors. This wizard walks 6 sections (quiet hours / smoking / pets / guests / property care / departure) and outputs a 25-40 rule document with the specifics that actually work — dB thresholds, time windows, fees, fee triggers.',
    ],
    'inside'     => [
    ],
    'for'        => [
      'Hosts who currently list 4 generic rules',
      'Multi-property operators standardizing',
      'Anyone who\'s lost a damage claim because the rule wasn\'t specific',
    ],
    'not'        => [
      'Hosts whose property manager handles all guest comms',
      'Hosts who use a SaaS like Touch Stay for rules',
      'Pure-passive Schedule E hosts not running ops',
    ],
    'faq'        => [
    ],
  ],
  'OPS-002' => [
    'sku'        => 'OPS-002',
    'slug'       => 'damage-claim-log',
    'name'       => 'The Damage Claim Log',
    'category'   => 'Operations / Daily Management',
    'price'      => '$17',
    'badge'      => '',
    'card_blurb' => 'AirCover damage log with 14-day countdown and a 12-item evidence checklist.',
    'mock_sub'   => 'When something breaks, this is the calm move.',
    'h1'         => 'When a guest breaks something, this is the calm move.',
    'sub'        => 'AirCover-ready damage claim log with a 14-day deadline countdown, a 12-item evidence checklist, and the recovery rate you can actually quote — so you stop submitting at 30% paid.',
    'pitch'      => [
      'A guest broke your coffee table at 11pm Saturday. By Tuesday you had receipts in three places, photos on your phone, and screenshots in the host app. AirCover paid 30%.',
      'The reason is not the platform. The reason is the submission.',
      'Active hosts file 2-6 claims a year. Median recovery on a clean submission is 78%. Median on a scrambled submission is 31%. The gap between those numbers — over a portfolio, over years — is a five-figure problem that no insurance product fixes.',
    ],
    'inside'     => [
      ['name' => 'Start', 'desc' => 'open-claim count, dollars at risk, deadline-watch list (top 5 claims by days remaining, color-coded)'],
      ['name' => 'Claims Register', 'desc' => '200-row master log. Date discovered, property, guest, channel, $ claimed, $ recovered, status, days-to-deadline (auto), recovery rate per claim'],
      ['name' => 'Claim Packet', 'desc' => 'single-claim worksheet. Six sections: incident, damage list, 12-item evidence checklist, comm log, timeline, outcome. Submit-ready gate at 75% completeness'],
      ['name' => 'Coverage Reference', 'desc' => 'AirCover (Airbnb), VRBO Property Damage Protection, Booking.com Partner Liability snapshots. Covered / not covered / filing window / evidence required / dispute escalation. "As of" stamped'],
      ['name' => 'Message Scripts', 'desc' => '5 copy-paste scripts: first contact, formal claim opening, evidence-request response, dispute/denial response, post-resolution review management'],
      ['name' => 'Annual Damage P&L', 'desc' => 'total claimed YTD, total recovered, recovery rate %, top-3 loss categories, per-property breakdown'],
      ['name' => 'Settings', 'desc' => 'property list, status dropdown, filing-window default, reference as-of stamp'],
    ],
    'for'        => [
      'Hosts who have ever felt the AirCover 14-day deadline panic',
      'Multi-property operators tracking claims across Airbnb, VRBO, and Booking.com',
      'Co-hosts and managers who file on owners\' behalf and need an evidence trail',
      'Hosts who want a recovery rate they can quote to a partner or insurer',
      'Anyone whose last claim was paid 30% and who never wants that to happen again',
    ],
    'not'        => [
      'Hosts who have never had a claim and don\'t intend to file one',
      'LTR landlords doing security-deposit work — different statutes, different process',
      'Hosts looking for a chat-bot that submits the claim for them — none exists, this is not it',
      'Anyone who treats damage as "a cost of doing business" and refuses to file',
      'Hosts looking for legal advice on disputed claims — see your attorney',
    ],
    'faq'        => [
      ['q' => 'Does this submit the claim for me?', 'a' => 'No. Airbnb, VRBO, and Booking.com require submission through their own portals. This workbook is the evidence packet, the deadline tracker, and the post-mortem record — everything outside the portal.'],
      ['q' => 'What if AirCover changes its policy?', 'a' => 'The Coverage Reference tab is "as of" stamped and points you to the platform help URL to verify. We update the workbook periodically. You re-stamp the date when you confirm.'],
      ['q' => 'Why isn\'t this on Etsy?', 'a' => 'Because a stripped Etsy Lite version of a claim packet is worse than no template. The deadline countdown and message scripts are not optional features — they are the product. We sell this on the own-site only.'],
      ['q' => 'How is this different from just using the Airbnb resolution center?', 'a' => 'The resolution center is a submission form. It does not track deadlines across multiple open claims, does not keep evidence in one place, does not produce an annual recovery rate, and does not exist on VRBO or Booking. This is the workspace that wraps all three platforms.'],
      ['q' => 'Does it work for direct-booking damage?', 'a' => 'Yes. Coverage Reference includes a fourth column for direct-booking claims (security deposit hold + your own insurance). Same evidence discipline.'],
      ['q' => 'Is the 14-day window the same on every platform?', 'a' => 'No — it\'s Airbnb\'s standard. VRBO and Booking.com have their own windows. The Coverage Reference tab lists each one. The Settings tab lets you override the default per-claim if you\'ve confirmed a different window with the platform.'],
    ],
  ],
  'FIN-001' => [
    'sku'        => 'FIN-001',
    'slug'       => 'revpar-dashboard',
    'name'       => 'The RevPAR Dashboard',
    'category'   => 'Financial / Accounting',
    'price'      => '$27',
    'badge'      => '',
    'card_blurb' => 'RevPAR + ADR + Occupancy with YoY, AirDNA comp, and a sensitivity simulator.',
    'mock_sub'   => 'Are you winning per available night — or just charging more?',
    'h1'         => 'Are you winning per available night — or just charging more?',
    'sub'        => 'RevPAR, ADR, Occupancy with YoY, AirDNA comp benchmark, and a sensitivity simulator. The KPIs the industry actually uses.',
    'pitch'      => [
      'Gross revenue is a vanity metric. Hosts who quote it are the same ones who cannot tell whether last quarter was real growth or a lucky weekend.',
      'The three numbers that matter — ADR, Occupancy, RevPAR — are what every market report, pricing tool, and STR investor uses. RevPAR is the one that captures both at once: revenue per available night. You cannot game it by pricing high and selling little.',
      'This dashboard computes all three correctly. It treats personal-use, maintenance, and owner-block nights the right way (excluded from the denominator — same convention as PriceLabs and AirDNA). It compares to last year. It pastes your AirDNA comp number for context. And it includes a sensitivity simulator so you can stop guessing whether to push ADR or push occupancy.',
    ],
    'inside'     => [
      ['name' => 'Start', 'desc' => 'headline KPIs in gold: portfolio YTD RevPAR, YoY delta, comp benchmark line, best/worst property. Inline glossary cards explain each metric in plain English'],
      ['name' => 'Property Setup', 'desc' => 'per-property: rooms, available nights baseline, blocked-night categories. 20-property capacity'],
      ['name' => 'Booking Log', 'desc' => 'TAX-002 column shape, 5,000-row capacity (paste-compatible from existing files)'],
      ['name' => 'Blocked-Night Log', 'desc' => 'separate table for personal use, maintenance, owner stays. 500-row capacity. The integrity differentiator'],
      ['name' => 'Daily Calendar', 'desc' => 'auto-pivoted, 365 rows × up to 20 properties. Each cell shows B / X / blank with conditional formatting'],
      ['name' => 'KPI Dashboard', 'desc' => '12 months × ADR / Occ / RevPAR per property + portfolio rollup. YoY delta column'],
      ['name' => 'Sensitivity Simulator', 'desc' => '3×2 scenario grid (ADR +$0/+$5/+$10 × Occ +0/+5pp) per property with revenue impact'],
      ['name' => 'Settings', 'desc' => 'properties, blocked-night categories, comp ADR, prior-year reference table'],
    ],
    'for'        => [
    ],
    'not'        => [
    ],
    'faq'        => [
      ['q' => 'Q: Why is the blocked-night method so important?', 'a' => 'Because it is the only one that produces an occupancy figure comparable to the rest of the industry. Templates that ignore blocks overstate your number. Templates that count blocks as available understate it. PriceLabs and AirDNA both exclude blocks from the denominator. This workbook does too. That means your number plays in the same conversation as theirs.'],
      ['q' => 'Q: I do not have AirDNA. Does the dashboard still work?', 'a' => 'Yes. The comp-benchmark row auto-hides when the comp Settings cell is empty. The dashboard then shows YoY comparison only. AirDNA is context, not required input.'],
      ['q' => 'Q: What is RevPAR in plain English?', 'a' => 'Revenue Per Available Night. RevPAR = Gross Revenue ÷ (Total Nights − Blocked Nights). It mathematically equals ADR × Occupancy. The advantage: it captures rate and occupancy together. You cannot game it.'],
      ['q' => 'Q: How do I get prior-year reference data if I never tracked this?', 'a' => 'Pull total gross revenue and total booked nights per property per month from your Airbnb / VRBO host dashboards. Enter on Settings rows 40-100. Roughly thirty minutes per property for a full prior year. Once entered, it does not need to be re-entered.'],
      ['q' => 'Q: Multi-year tracking?', 'a' => 'One workbook per tax year, by design. Re-run annually with prior year as reference. The daily-calendar pivot degrades above one year of data.'],
      ['q' => 'Q: Does this work in Google Sheets?', 'a' => 'Yes. The Daily Calendar pivot may take 10-15 seconds to render on first load — Sheets handles array formulas slightly slower than Excel. After load, scrolling is smooth.'],
    ],
  ],
  'FIN-003' => [
    'sku'        => 'FIN-003',
    'slug'       => 'cash-flow-forecaster',
    'name'       => 'The Cash-Flow Forecaster',
    'category'   => 'Financial Dashboard',
    'price'      => '$47',
    'badge'      => '',
    'card_blurb' => '12-month forward cash flow forecaster. Spot the months that go red — before they happen.',
    'mock_sub'   => 'See the months that go negative before they happen.',
    'h1'         => 'See the months that go negative — before they happen.',
    'sub'        => '12-month forward cash flow forecaster for STR portfolios. Confirmed bookings + seasonal projection + recurring expenses + tax payments. Solves the "ran out of cash in February" failure mode.',
    'pitch'      => [
      'Seasonal STRs run out of operating cash every February. Bookings thin, mortgage still due, insurance just renewed. The host who doesn\'t see it coming panic-lists at low rates and tanks their search ranking. This workbook is the forward-looking forecast. Confirmed + projected revenue + recurring expenses + planned one-offs + quarterly tax = 12 months ahead, with negative-month flags so you can move expenses or pull from reserves before the panic.',
    ],
    'inside'     => [
    ],
    'for'        => [
      'Portfolio operators (3+ properties)',
      'Seasonal-market hosts (beach, ski, mountain)',
      'Hosts who\'ve moved a payment date due to cash tightness',
    ],
    'not'        => [
      'Single-property hosts (use TAX-002 instead)',
      'Steady-state markets with no seasonality',
      'Hosts with 12+ months operating reserve already',
    ],
    'faq'        => [
    ],
  ],
  'ACQ-001' => [
    'sku'        => 'ACQ-001',
    'slug'       => 'deal-analyzer',
    'name'       => 'The Deal Analyzer',
    'category'   => 'Acquisition / Underwriting',
    'price'      => '$27',
    'badge'      => '',
    'card_blurb' => 'STR underwriting workbook. Stress-tested. Yes-or-no on a property in 10 minutes.',
    'mock_sub'   => 'Yes-or-no on a property in 10 minutes.',
    'h1'         => 'Yes-or-no on a property in 10 minutes.',
    'sub'        => 'STR underwriting workbook with stress test, Y1-vs-stabilized toggle, and a one-page CPA summary — so you stop closing on AirDNA-median deals that fail the moment ADR slips.',
    'pitch'      => [
      'You\'re looking at three Zillow listings tonight. AirDNA wants $40 per property. The BiggerPockets calculator was built for long-term rentals. The BPCalc spreadsheet you downloaded last year is broken from a column rename.',
      'You need a yes/no on each in 10 minutes — and you need it to be the kind of yes/no your CPA, your spouse, and your lender will not argue with.',
      'Twenty-five inputs across four categories — property, market, costs, finance — and one verdict at the end. Cash-on-cash, cap rate, DSCR, and 5-year IRR shown so you can see why. Stress test against ADR -10%, occupancy to 55%, and expenses +20% so you know the deal still works when the AirDNA optimism wears off.',
    ],
    'inside'     => [
      ['name' => 'Start', 'desc' => 'property name + address, large gold/green/red verdict, Y1 and stabilized cash flow side-by-side, stress-test verdict (Full)'],
      ['name' => 'Property', 'desc' => 'address, type (single-family / cabin / condo / multi-unit / glamping / other), beds, baths, sqft, year built, lot type, key amenities (hot tub, pool, view) for ADR adjustment'],
      ['name' => 'Market', 'desc' => 'ADR base + 3-comp average, stabilized occupancy %, Y1 occupancy % (default 65% of stabilized), avg LOS, peak/off-peak split, seasonality factor. "Paste from AirDNA" callout with instructions'],
      ['name' => 'Costs', 'desc' => '15 cost lines mirroring the FIN-002 + TAX-002 column shape so you can paste between SKUs. Maintenance reserve 5% default, capex reserve 3% default, platform commission 15% default'],
      ['name' => 'Finance', 'desc' => 'purchase price, down %, loan amount (auto), rate, term, closing, rehab, furnishing. Amortization-derived monthly + annual debt service displayed'],
      ['name' => 'Verdict', 'desc' => 'cash-on-cash, cap rate, DSCR, 5-year IRR, break-even occupancy, verdict string keyed to BiggerPockets STR cash-on-cash benchmark. Y1/Stabilized toggle (Full)'],
      ['name' => 'Stress Test (Full only)', 'desc' => 'Base / Down-10% / Stress side-by-side. Each scenario re-evaluates the full verdict'],
      ['name' => 'CPA / Partner Summary (Full only)', 'desc' => '1-page printable, portrait letter. Property + key terms + 5-year pro-forma + verdict + notes box'],
    ],
    'for'        => [
      'Side-Hustle Sam scaling to property #2 or #3',
      'Semi-Pro Sarah running 5-10 underwrites before pulling the trigger',
      'Investors validating their first deal alongside Cost-to-Launch',
      'Buyers who have ever closed on an AirDNA-median deal and watched Y1 occupancy come in 30 points lower',
      'Sellers\' agents pre-qualifying STR-suitable listings for their buyer',
    ],
    'not'        => [
      'Hedge-fund analysts running 50-property portfolios — use Argus',
      'Anyone expecting live AirDNA API integration (legally not allowed)',
      'LTR landlords — different cost structure, use a BP calculator',
      'Buyers who don\'t believe Y1 ≠ stabilized — this workbook will frustrate you',
      'Anyone wanting a chat-bot to recommend deals — this is a calculator, not an advisor',
    ],
    'faq'        => [
      ['q' => 'Lite or Full?', 'a' => 'If you\'re underwriting one or two properties a year, Lite ($27) is enough. If you\'re running 5+ deals through the workbook before pulling the trigger, the $20 upgrade to Full pays for itself the first time the stress test catches a deal that looked good on paper. The Lite has no stress test, no Y1/Stabilized toggle, and no printable summary.'],
      ['q' => 'Does it pull live AirDNA data?', 'a' => 'No. AirDNA is a paid API and not legally re-distributable inside an Excel template. You paste ADR and occupancy from AirDNA (or your own comp work) into the Market tab. Everything else calculates.'],
      ['q' => 'What\'s the difference between Y1 and stabilized cash flow?', 'a' => 'Y1 occupancy for a new STR is typically 65% of stabilized — BiggerPockets community consensus, cited in the workbook. Most failed acquisitions assume Y1 = stabilized. The Full toggles between them on the Verdict tab.'],
      ['q' => 'What appreciation rate does IRR assume?', 'a' => '3% annual appreciation, 6% sell costs, 5-year hold. Editable assumption cells on the Verdict tab.'],
      ['q' => 'Can I compare three properties side-by-side?', 'a' => 'One property per workbook (this is wizard mode). Multi-property comparison is a separate SKU. Most users duplicate the file once per candidate, then transfer the Verdict outputs into a 3-property summary.'],
      ['q' => 'How is this different from the BiggerPockets calculator?', 'a' => 'BP\'s free calculator is built for long-term rentals — no avg LOS, no platform commission, no STR-specific occupancy modeling, no AirCover or cleaning fee mechanics. This workbook is built for short-term rentals from the inputs up.'],
    ],
  ],
  'LGL-001' => [
    'sku'        => 'LGL-001',
    'slug'       => 'license-renewal-calendar',
    'name'       => 'The Renewal Calendar',
    'category'   => 'Legal & Compliance',
    'price'      => '$17',
    'badge'      => '',
    'card_blurb' => 'Permit + license renewal calendar. 60-day yellow flags, 30-day red flags. Never lapse.',
    'mock_sub'   => 'Every renewal date, ahead of you. Not behind.',
    'h1'         => 'Every renewal date, ahead of you. Not behind.',
    'sub'        => 'STR license + permit renewal calendar for Airbnb / VRBO hosts. 60-day yellow flags, 30-day red flags. Don\'t lose your listing because a permit lapsed.',
    'pitch'      => [
      'A $2,500 STR permit you forgot to renew can take your $48,000/year listing offline. The city sends one notice (sometimes none). Airbnb gets the city\'s notice and deactivates. Now you\'re scrambling to re-register as a NEW applicant, and your peak season is gone. This workbook is the calendar that prevents it. Yellow at 60 days. Red at 30. Renewals completed before the cleaner has noticed.',
    ],
    'inside'     => [
    ],
    'for'        => [
      'Single-property hosts who can\'t afford one missed deadline',
      'Multi-jurisdiction operators (cities + states)',
      'Hosts in regulated markets (Joshua Tree, Sedona, Nashville, Austin, NYC, SF)',
    ],
    'not'        => [
      'Hosts in unregulated markets with no permits at all',
      'Pure long-term landlords (different regulatory regime)',
      'Hosts whose PM handles all permits',
    ],
    'faq'        => [
    ],
  ],
];