#!/usr/bin/env node
// is-probe.mjs
// Live read-only probe of the IS tenant: resolves opaque list IDs and product IDs
// into yaml files that other scripts can import.
//
// Writes:
//   infrastructure/influencersoft/lists.yaml
//   infrastructure/influencersoft/products.yaml
//
// Usage (from Excel-Templates root, NOT worktree):
//   node scripts/is-probe.mjs

import { writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { getAllGroups, getGoods, getBaseUrl } from "./lib/influencersoft.mjs";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const INFRA_DIR = join(REPO_ROOT, "infrastructure", "influencersoft");

function yamlEscape(v) {
  if (v === null || v === undefined) return "null";
  const s = String(v);
  return /[:\#\n"\'{}\[\],&\*!\|<>=%@`?]/.test(s) || s.includes(" ")
    ? `"${s.replace(/"/g, '\\"')}"`
    : s;
}

function renderListsYaml(groups) {
  const lines = [
    `# InfluencerSoft list/group ID resolution map.`,
    `# Auto-generated by scripts/is-probe.mjs — DO NOT HAND-EDIT.`,
    `# Generated: ${new Date().toISOString()}`,
    `# Tenant: ${getBaseUrl()}`,
    ``,
    `lists:`,
  ];
  for (const g of groups) {
    const id = g.id ?? g.group_id ?? g.list_id;
    const name = g.name ?? g.group_name ?? g.list_name;
    lines.push(`  - id: ${yamlEscape(id)}`);
    lines.push(`    name: ${yamlEscape(name)}`);
    if (g.count != null) lines.push(`    count: ${g.count}`);
  }
  return lines.join("\n") + "\n";
}

function renderProductsYaml(goods) {
  const lines = [
    `# InfluencerSoft product/good ID resolution map.`,
    `# Auto-generated by scripts/is-probe.mjs — DO NOT HAND-EDIT.`,
    `# Generated: ${new Date().toISOString()}`,
    ``,
    `products:`,
  ];
  if (!goods.length) {
    lines.push(`  []  # catalog empty — populate via IS UI then re-probe`);
    return lines.join("\n") + "\n";
  }
  for (const p of goods) {
    const id = p.id ?? p.product_id ?? p.good_id;
    const name = p.name ?? p.product_name ?? p.good_name;
    lines.push(`  - id: ${yamlEscape(id)}`);
    lines.push(`    name: ${yamlEscape(name)}`);
    if (p.price != null) lines.push(`    price: ${p.price}`);
    if (p.sku) lines.push(`    sku: ${yamlEscape(p.sku)}`);
  }
  return lines.join("\n") + "\n";
}

async function main() {
  if (!existsSync(INFRA_DIR)) await mkdir(INFRA_DIR, { recursive: true });
  console.log(`Probing ${getBaseUrl()} ...`);

  const groupsRes = await getAllGroups();
  const groups = Array.isArray(groupsRes.result) ? groupsRes.result : [];
  console.log(`  GetAllGroups: ${groups.length} group(s)`);

  const goodsRes = await getGoods();
  const goods = Array.isArray(goodsRes.result) ? goodsRes.result : [];
  console.log(`  GetGoods: ${goods.length} product(s)`);

  await writeFile(join(INFRA_DIR, "lists.yaml"), renderListsYaml(groups));
  await writeFile(join(INFRA_DIR, "products.yaml"), renderProductsYaml(goods));

  console.log(`\n  WROTE infrastructure/influencersoft/lists.yaml`);
  console.log(`  WROTE infrastructure/influencersoft/products.yaml`);
}

main().catch((err) => {
  console.error(`PROBE FAILED: ${err.message}`);
  process.exit(1);
});
