#!/usr/bin/env node
/**
 * sync-env.mjs — fan-out the root .env into per-project .env.local files.
 *
 * USAGE
 *   pnpm sync:env             # generate from root .env
 *   pnpm sync:env --check     # verify generated files match (CI mode)
 *   pnpm sync:env --print     # print the per-project key listing without writing
 *
 * INPUT
 *   .env                — single source of truth (gitignored). User edits this.
 *   env.config.json     — declares which keys each project receives (committed).
 *
 * OUTPUT
 *   <project>/.env.local — generated per-project file (gitignored). DO NOT EDIT.
 *
 * GUARANTEES
 *   - Never prints secret values to stdout (only key names + boolean "set/empty")
 *   - Files start with a "DO NOT EDIT" header
 *   - Files end with a deterministic checksum line so --check can verify they
 *     match the current root .env without re-reading values
 *   - Missing keys are written as empty (KEY=) so dotenv still picks them up
 */

import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const ROOT_ENV_PATH = join(REPO_ROOT, '.env');
const CONFIG_PATH = join(REPO_ROOT, 'env.config.json');
const GENERATED_HEADER =
  '# GENERATED by `pnpm sync:env`. DO NOT EDIT — your changes will be overwritten.\n' +
  '# Source: <repo-root>/.env\n' +
  '# To change a value, edit <repo-root>/.env and run `pnpm sync:env`.\n' +
  '\n';

const argv = process.argv.slice(2);
const MODE = argv.includes('--check') ? 'check' : argv.includes('--print') ? 'print' : 'write';

function parseEnv(text) {
  const out = new Map();
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1);
    // Strip surrounding double-quotes if present (dotenv convention)
    if (val.length >= 2 && val.startsWith('"') && val.endsWith('"')) {
      val = val.slice(1, -1);
    }
    out.set(key, val);
  }
  return out;
}

function resolveLiteral(literal, ctx) {
  return literal.replace(/\$([A-Z_][A-Z_0-9]*)/g, (_, name) => ctx.get(name) ?? '');
}

function shaShort(s) {
  return createHash('sha256').update(s).digest('hex').slice(0, 12);
}

function buildProjectEnv(projectName, projectCfg, sharedKeys, rootEnv) {
  const lines = [GENERATED_HEADER];
  const localCtx = new Map();
  const seen = new Set();

  // Shared section
  if (sharedKeys.length > 0) {
    lines.push(`# --- shared keys ---\n`);
    for (const key of sharedKeys) {
      const value = rootEnv.get(key) ?? '';
      localCtx.set(key, value);
      lines.push(`${key}=${value}\n`);
      seen.add(key);
    }
    lines.push('\n');
  }

  // Project-specific section
  if (projectCfg.include.length > 0) {
    lines.push(`# --- ${projectName} project keys ---\n`);
    for (const entry of projectCfg.include) {
      if (typeof entry === 'string') {
        const value = rootEnv.get(entry) ?? '';
        localCtx.set(entry, value);
        lines.push(`${entry}=${value}\n`);
        seen.add(entry);
      } else if (entry.literal) {
        const resolved = resolveLiteral(entry.literal, localCtx);
        const eq = resolved.indexOf('=');
        if (eq !== -1) {
          const k = resolved.slice(0, eq);
          const v = resolved.slice(eq + 1);
          localCtx.set(k, v);
          if (!seen.has(k)) {
            lines.push(`${resolved}\n`);
            seen.add(k);
          }
        }
      } else if (entry.from && entry.to) {
        const value = rootEnv.get(entry.from) ?? '';
        localCtx.set(entry.to, value);
        if (!seen.has(entry.to)) {
          lines.push(`${entry.to}=${value}\n`);
          seen.add(entry.to);
        }
      }
    }
    lines.push('\n');
  }

  const body = lines.join('');
  const checksum = shaShort(body);
  return body + `# checksum: ${checksum}\n`;
}

function summary(rootEnvMap, projectName, contents) {
  // Print key=set/empty without leaking values
  const parsed = parseEnv(contents);
  const setCount = [...parsed.values()].filter((v) => v.length > 0).length;
  const totalCount = parsed.size;
  return `${projectName.padEnd(28)}  ${setCount}/${totalCount} keys set`;
}

function main() {
  if (!existsSync(CONFIG_PATH)) {
    console.error(`✗ env.config.json not found at ${CONFIG_PATH}`);
    process.exit(2);
  }
  if (!existsSync(ROOT_ENV_PATH)) {
    console.error(`✗ Root .env not found at ${ROOT_ENV_PATH}`);
    console.error(`  Copy .env.example to .env and fill in values, then re-run.`);
    process.exit(2);
  }

  const config = JSON.parse(readFileSync(CONFIG_PATH, 'utf-8'));
  const rootEnvText = readFileSync(ROOT_ENV_PATH, 'utf-8');
  const rootEnv = parseEnv(rootEnvText);

  const projectNames = Object.keys(config.projects);
  let mismatchCount = 0;

  for (const projectName of projectNames) {
    const projectCfg = config.projects[projectName];
    const projectDir = join(REPO_ROOT, projectName);
    if (!existsSync(projectDir) || !statSync(projectDir).isDirectory()) {
      console.warn(`  skip: ${projectName} (directory not found)`);
      continue;
    }
    const targetPath = join(projectDir, '.env.local');
    const contents = buildProjectEnv(projectName, projectCfg, config.shared ?? [], rootEnv);

    if (MODE === 'print') {
      console.log(summary(rootEnv, projectName, contents));
      continue;
    }

    if (MODE === 'check') {
      if (!existsSync(targetPath)) {
        console.error(`✗ ${targetPath} missing`);
        mismatchCount++;
        continue;
      }
      const onDisk = readFileSync(targetPath, 'utf-8');
      if (onDisk !== contents) {
        console.error(`✗ ${targetPath} out of date — run \`pnpm sync:env\``);
        mismatchCount++;
      } else {
        console.log(`✓ ${projectName}`);
      }
      continue;
    }

    // Safety: refuse to overwrite a hand-edited .env.local (no generator header).
    if (existsSync(targetPath)) {
      const onDisk = readFileSync(targetPath, 'utf-8');
      if (!onDisk.startsWith('# GENERATED by `pnpm sync:env`')) {
        console.error(`✗ ${targetPath} appears hand-edited (no generator header).`);
        console.error(`  Refusing to overwrite. Run \`pnpm migrate:env\` to merge it into root .env first,`);
        console.error(`  or back it up and delete it, then re-run \`pnpm sync:env\`.`);
        process.exit(3);
      }
    }

    writeFileSync(targetPath, contents);
    console.log(`  wrote ${projectName}/.env.local — ${summary(rootEnv, projectName, contents).split(/\s{2,}/)[1]}`);
  }

  if (MODE === 'check') {
    if (mismatchCount > 0) {
      console.error(`\n${mismatchCount} project(s) out of sync. Run \`pnpm sync:env\` and commit nothing — derived files are gitignored.`);
      process.exit(1);
    }
    console.log(`\n✓ all per-project .env.local files in sync with root .env`);
  } else if (MODE === 'write') {
    console.log(`\n✓ sync-env: ${projectNames.length} project file(s) regenerated from root .env`);
  }
}

main();
