import { createEvents, type EventAttributes } from 'ics';
import type { ScheduleResult } from '@lib/calc/maintenance-schedule';

export function buildIcs(r: ScheduleResult): string {
  const events: EventAttributes[] = r.events.map(e => {
    const [y, m, d] = e.date.split('-').map(Number);
    return {
      title: `Maintenance: ${e.name}`,
      start: [y, m, d, 9, 0],
      duration: { hours: 1 },
      description: `Recurs every ${e.cadenceDays} days. Generated by strops.tools.`,
      productId: 'strops.tools/ics',
    };
  });
  const { error, value } = createEvents(events);
  if (error) throw error;
  return value!;
}

export function downloadIcs(content: string, filename: string) {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: 'text/calendar' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  (window as any).gtag && (window as any).gtag('event', 'ics_downloaded', { filename });
}
