/**
 * ICS (RFC 5545) calendar export for the maintenance schedule.
 *
 * Uses the `ics` package — it handles the CRLF line endings, line folding,
 * and DTSTAMP/UID generation for us. We render each event at 09:00 local on
 * its scheduled date with a 1hr duration; description includes the cadence
 * and a strops.tools attribution.
 *
 * `downloadIcs` is browser-side only (no-op in SSR). GA4 fires
 * `ics_downloaded` so Phase 5 analytics can attribute the export funnel.
 */

import { createEvents, type EventAttributes } from 'ics';
import type { ScheduleResult } from '../calc/maintenance-schedule';

export function buildIcs(r: ScheduleResult): string {
  const events: EventAttributes[] = r.events.map(e => {
    const [y, m, d] = e.date.split('-').map(Number);
    return {
      title: `Maintenance: ${e.name}`,
      start: [y, m, d, 9, 0],
      duration: { hours: 1 },
      description: `Recurs every ${e.cadenceDays} days. Generated by strops.tools.`,
      productId: 'strops.tools/ics',
    };
  });
  if (events.length === 0) {
    // Even an empty calendar must be a valid ICS doc.
    return [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//strops.tools//Maintenance Schedule//EN',
      'CALSCALE:GREGORIAN',
      'END:VCALENDAR',
    ].join('\r\n');
  }
  const { error, value } = createEvents(events);
  if (error) throw error;
  return value as string;
}

export function downloadIcs(content: string, filename: string): void {
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  const blob = new Blob([content], { type: 'text/calendar' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  (window as unknown as { gtag?: (...args: unknown[]) => void }).gtag?.('event', 'ics_downloaded', {
    filename,
  });
}
